# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='ADMember',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='loginId',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
