# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_auto_20171001_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admember',
            name='addressM',
        ),
        migrations.RemoveField(
            model_name='admember',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='admember',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='admember',
            name='phoneM',
        ),
    ]
