# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visiter', '0002_auto_20170926_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='loginId',
        ),
        migrations.AddField(
            model_name='registration',
            name='prName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visiter.Member'),
        ),
    ]
