# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visiter', '0004_auto_20170929_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
